"""empty message

Revision ID: 73710bfeaedf
Revises: 
Create Date: 2020-02-22 14:47:16.554277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73710bfeaedf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('phoneNum', sa.String(length=15), nullable=True),
    sa.Column('mobileNum', sa.String(length=15), nullable=True),
    sa.Column('emailAddress', sa.String(length=255), nullable=True),
    sa.Column('invoceNum', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('suburb', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('postCode', sa.Integer(), nullable=True),
    sa.Column('directions', sa.String(length=255), nullable=True),
    sa.Column('propertyType', sa.String(length=255), nullable=True),
    sa.Column('storyType', sa.String(length=255), nullable=True),
    sa.Column('existingSystem', sa.String(length=255), nullable=True),
    sa.Column('switchboardSpecialRequirements', sa.String(length=255), nullable=True),
    sa.Column('undergroundPowerRequirements', sa.String(length=255), nullable=True),
    sa.Column('dataCableRequirements', sa.String(length=255), nullable=True),
    sa.Column('meteringType', sa.String(length=255), nullable=True),
    sa.Column('subMetering', sa.String(length=255), nullable=True),
    sa.Column('retailer', sa.String(length=255), nullable=True),
    sa.Column('phase', sa.String(length=255), nullable=True),
    sa.Column('poleNum', sa.String(length=255), nullable=True),
    sa.Column('transformerSize', sa.String(length=255), nullable=True),
    sa.Column('serviceType', sa.String(length=255), nullable=True),
    sa.Column('serviceMainsLen', sa.Integer(), nullable=True),
    sa.Column('serviceMainsSize', sa.Integer(), nullable=True),
    sa.Column('consumerMainsLen', sa.Integer(), nullable=True),
    sa.Column('consumerMainsSize', sa.Integer(), nullable=True),
    sa.Column('FSSLen', sa.Integer(), nullable=True),
    sa.Column('FSSSize', sa.Integer(), nullable=True),
    sa.Column('loadProfile', sa.String(length=255), nullable=True),
    sa.Column('quater1DailyKWH', sa.String(length=255), nullable=True),
    sa.Column('quater2DailyKWH', sa.String(length=255), nullable=True),
    sa.Column('quater3DailyKWH', sa.String(length=255), nullable=True),
    sa.Column('quater4DailyKWH', sa.String(length=255), nullable=True),
    sa.Column('currentElectricityCost', sa.String(length=255), nullable=True),
    sa.Column('currentFitRate', sa.String(length=255), nullable=True),
    sa.Column('heatingSystem1', sa.String(length=255), nullable=True),
    sa.Column('heatingSystem2', sa.String(length=255), nullable=True),
    sa.Column('coolingSystems', sa.String(length=255), nullable=True),
    sa.Column('pool', sa.String(length=255), nullable=True),
    sa.Column('pumping', sa.String(length=255), nullable=True),
    sa.Column('hotWater', sa.String(length=255), nullable=True),
    sa.Column('floorHeating', sa.String(length=255), nullable=True),
    sa.Column('otherSigLoads', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('inverterLocationAndMounting', sa.String(length=255), nullable=True),
    sa.Column('roofType', sa.String(length=255), nullable=True),
    sa.Column('panelOreintation', sa.String(length=255), nullable=True),
    sa.Column('roofHeight', sa.String(length=255), nullable=True),
    sa.Column('shading', sa.String(length=255), nullable=True),
    sa.Column('monitoring', sa.String(length=255), nullable=True),
    sa.Column('installationDifficulty', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design__item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('item')
    op.drop_table('design__item')
    op.drop_table('design')
    op.drop_table('customer')
    op.drop_table('category')
    # ### end Alembic commands ###
